const fieldDisplayMappingPilots = {
  fullName: "Họ và tên",
  PHCDD: "PH CCĐ",
  gender: "Giới tính",
  ID: "ID",
  rank: "Cấp bậc",
  unit: "Đơn vị",
  hatLining: "Lót mũ bay",
  flyingClothes: "Quần áo công tác bay",
  flyingUnderwear: "Quần áo lót bay",
  flyingLeatherJacket: "Áo da bay",
  sweater: "Áo len",
  skydivingShoes: "Giày da nhảy dù",
  flyingShoes: "Giày da bay",
  warmClothes: "Áo ấm",
  physicalTrainingClothes: "Quần áo RLTL",
  flyingClothesSummer: "Quần áo công tác bay hè",
  flyingClothesWinter: "Quần áo công tác bay đông",
  leatherGloves: "Găng tay da",
  fiberGloves: "Găng tay sợi",
  flyingShoesHigh: "Giày bay cao cổ",
  flyingShoesLow: "Giày bay thấp cổ",
  socks: "Bít tất",
  mattress: "Đệm nằm",
  mattressCover: "Ga đệm",
  mat: "Chiếu",
  tulleCurtain: "Màn tuyn",
  hatLiningsz: "Lót mũ bay",
  flyingUnderwearsz: "Quần áo lót bay",
  flyingLeatherJacketsz: "Áo da bay",
  sweatersz: "Áo len",
  skydivingShoessz: "Giày nhảy dù",
  warmClothessz: "Áo ấm",
  physicalTrainingClothessz: "Quần áo RLTL",
};
export default fieldDisplayMappingPilots;
