const fieldDisplayMapping = {
  fullName: "Họ và tên",
  PHCDD: "PH CCĐ",
  gender: "Giới tính",
  ID: "ID",
  rank: "Cấp bậc",
  unit: "Đơn vị",
  lotteryNumber: "Sổ QTCN số",
  uniform: "Quân phục",
  shoe: "Giày",
  hat: "Mũ",
  mat: "Chiếu",
  duaration: "QT niên hạn",
  underwear: "Quần lót",
  tShirt: "Áo lót",
  towel: "Khăn mặt",
  sock: "Bít tất",
  leatherShoe: "Giày da",
  womanLeatherGie: "Ghệt da nữ",
  trouser: "Quần dài",
  shortSleevedShirt: "Áo SMNT",
  winterMilitaryUniform: "Quân phục đông",
  summerVestment: "Lễ phục hè",
  winterVestment: "Lễ phục đông",
  sandal: "Dép nhựa",
  sedgeMat: "Chiếu cói",
  quiltCover: "Vỏ chăn",
  tulleCurtain: "Màn tuyn",
  balo: "Balo",
  baloLining: "Túi lót balo",
  longSleevedShirt: "Áo SMDT",
  longSleevedShirtWhite: "Áo SMDT trắng",
  liningShirt: "Áo chít gấu",
  warmClothes: "Áo ấm",
  seasonalClothes: "Áo xuân thu",
  rainSuit: "QA mưa SQ",
  hardHat: "Mũ cứng",
  kepiHat: "Mũ Kêpi",
  caravat: "Caravat",
  caravatClip: "Kẹp caravat",
  pillow: "Gối mút hơi",
  leatherBelt: "Dây lưng nhỏ",
  armorialMilitary28: "Quân hiệu ĐK28mm",
  armorialMilitary33: "Quân hiệu ĐK33mm",
  rankInsignia: "Cấp hiệu",
  branchInsignia: "Phù hiệu",
  dayChienThang: "Dây chiến thắng",
  receiver: "Người nhận",
  criterionOf: "Tiêu chuẩn của",
  tranferFrom: "Chuyển từ",
  moveInTime: "Thời gian chuyển đến",
  fromAnyYear: "Bảo đảm từ năm",
  bookSubmitter: "Người nộp sổ QTCN",
  dateOfSubmission: "Ngày nộp sổ QTCN",
  tranferTo: "Chuyển đến",
  toAnyYear: "Bảo đảm đến năm",
  dateMove: "Ngày chuyển đi",
  numberOfDecision: "Số quyết định",
  internalTransfer: "Chuyển nội bộ",
};
export default fieldDisplayMapping;
