const express = require('express')
const router = express.Router()


const listQuantrangController = require('../controllers/quantrang/listQuantrangController')
const individualController = require('../controllers/quantrang/individualController')
const criterionController = require('../controllers/quantrang/criterionController')
const dispensationController = require('../controllers/quantrang/dispensationController')
const increaseController = require('../controllers/quantrang/increaseController')
const decreaseController = require('../controllers/quantrang/decreaseController')
const statisticalController = require('../controllers/quantrang/statisticalController')

router.get('/individual', individualController.render)
router.patch('/individual/:id', individualController.update) 
router.get('/criterion', criterionController.render)
router.get('/criterion/update', criterionController.renderUpdate)
router.post('/criterion', criterionController.create)
router.post('/increase/temporarySave/update', increaseController.temporaryUpdate)
router.delete('/increase/temporarySave/remove', increaseController.temporaryRemove)
router.post('/increase/temporarySave', increaseController.temporarySave)
router.get('/increase/temporarySave', increaseController.getTemporarySaves)
router.post('/increase', increaseController.increase)
router.post('/increase/filter', increaseController.filter)
router.get('/increase/list', increaseController.list)
router.get('/decrease/list', decreaseController.list)
router.post('/decrease/temporarySave/update', decreaseController.temporaryUpdate)
router.delete('/decrease/temporarySave/remove', decreaseController.temporaryRemove)
router.post('/decrease/temporarySave', decreaseController.temporarySave)
router.get('/decrease/temporarySave', decreaseController.getTemporarySaves)
router.post('/decrease/filter', decreaseController.filter)
router.get('/decrease', decreaseController.render)
router.post('/decrease', decreaseController.decrease)
router.get('/increase', increaseController.render)
router.put('/criterion', criterionController.update)
router.get('/dispensation/getQRCode', dispensationController.getQRCodeData)
router.get('/dispensation', dispensationController.render)
router.post('/import', listQuantrangController.import)
router.patch('/add', listQuantrangController.add)
router.get('/statistical', statisticalController.render)
router.get('/search', listQuantrangController.search )
router.get('/', listQuantrangController.render);


module.exports = router